{% set version = "12.6.3" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-dev 12.6.77
    - cuda-cccl_{{ target_platform }} 12.6.77
    - cuda-profiler-api 12.6.77
    - cuda-driver-dev 12.6.77    # [linux]
    - cuda-nvrtc-dev 12.6.85
    - cuda-opencl-dev 12.6.77    # [linux64 or win]
    - libcublas-dev 12.6.4.1
    - libcufft-dev 11.3.0.4
    - libcufile-dev 1.11.1.6       # [linux]
    - libcurand-dev 10.3.7.77
    - libcusolver-dev 11.7.1.2
    - libcusparse-dev 12.5.4.2
    - libnpp-dev 12.3.1.54
    - libnvfatbin-dev 12.6.77
    - libnvjitlink-dev 12.6.85
    - libnvjpeg-dev 12.3.3.54

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
